version: '2'

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: Torni-Juegos # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding

  express:
    build: expressServer
    ports:
      - "3000:3000"
    links:
      - database

  database: # name of the third service
    build: dockerMongo # specify the directory of the Dockerfile
    ports:
      - "27017:27017" # specify port forewarding
